name: Mantener Streamlit Despierto

on:
  schedule:
    # Se ejecuta cada 10 horas (formato cron)
    - cron: '*/1 * * * *'

  workflow_dispatch: # Permite ejecutarlo manualmente para probar

jobs:
  awake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Git y realizar commit vacío
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "Commit automático para evitar hibernación"
          git push
